twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
     # ajouté pour pouvoir bénéficier dans tout le projet de la mise en page BS pour les formulaires
    form_themes: ['bootstrap_4_layout.html.twig']
